spring:
  cloud:
    config:
      failFast: true
      uri: http://localhost:8888
      name: user-service
      profile: ${config.profile:dev}
      discovery:
        serviceId: config-server
        enabled: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
